### ISSUE TITLE
Demo may need to updated

### ISSUE THREAD

**Issue by joshua-stone** [ascent12/compositor-killer#1]
I built `compositor-killer` and ran it with a fairly high number of iterations like `./build/compositor-killer -i 100000` on my laptop running Intel UHD graphics. During the first 10s-15s of runtime Gnome Shell will be sluggish, but the window then gets "stuck" after about 60-70 frames:

![image](https://github.com/ascent12/compositor-killer/assets/8183967/699fac0f-bcc9-4891-bcb1-c30dec5dba48)

The system does not hang at all once it gets to that point.

I'm wondering if this behavior is expected now that [explicit sync is implemented in Wayland compositors and Mesa](https://gitlab.freedesktop.org/wayland/wayland-protocols/-/merge_requests/90), or if the demo may need to be updated to leverage the explicit sync protocol.

**Comment by ascent12** [comment]
Maybe your GPU killed the job/context because it was taking too long. My AMD one definitely does that when you give it ridiculous arguments, but will also generate SIGABRT.
This isn't intended to be a high quality program, it's just testing something extremely specific, and it still works. I don't really care enough to look into it more.
